# Generated by Django 4.1.7 on 2023-08-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbook',
            name='publication_date',
        ),
    ]
